// <auto-generated />
using System;
using HsPXL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HsPXL.Migrations
{
    [DbContext(typeof(HsPXLContext))]
    [Migration("20201119155119_UpdateDataBank2")]
    partial class UpdateDataBank2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HsPXL.Models.Cursus", b =>
                {
                    b.Property<int>("CursusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CursusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HandboekID")
                        .HasColumnType("int");

                    b.Property<int>("Studiepunten")
                        .HasColumnType("int");

                    b.HasKey("CursusID");

                    b.HasIndex("HandboekID");

                    b.ToTable("Cursus");
                });

            modelBuilder.Entity("HsPXL.Models.HandBoek", b =>
                {
                    b.Property<int>("HandBoekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Afbeelding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CursusID")
                        .HasColumnType("int");

                    b.Property<decimal>("KostPrijs")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("UitgiftDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("HandBoekID");

                    b.HasIndex("CursusID");

                    b.ToTable("HandBoek");
                });

            modelBuilder.Entity("HsPXL.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("StudentID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("HsPXL.Models.Cursus", b =>
                {
                    b.HasOne("HsPXL.Models.HandBoek", "handboek")
                        .WithMany()
                        .HasForeignKey("HandboekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HsPXL.Models.HandBoek", b =>
                {
                    b.HasOne("HsPXL.Models.Cursus", null)
                        .WithMany("HandBoeken")
                        .HasForeignKey("CursusID");
                });
#pragma warning restore 612, 618
        }
    }
}
